services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file:
      - ../../global.env
      - private.env
    environment:
      - VPN_TYPE=openvpn
      - VPN_SERVICE_PROVIDER=surfshark
      - FIREWALL_VPN_INPUT_PORTS=8080
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16
      - UPDATER_PERIOD=24h
    volumes:
      - /srv/torrent-client/gluetun:/gluetun
    ports:
      - "127.0.0.1:8080:8080/tcp"
    networks:
      - proxy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8000/v1/openvpn/status | grep -q '\"status\":\"running\"' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    env_file:
      - ../../global.env
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
      - WEBUI_PORT=8080
    volumes:
      - /srv/torrent-client/qbittorrent/config:/config
      - /mnt/media/torrents:/downloads
    depends_on:
      gluetun:
        condition: service_healthy

networks:
  proxy:
    external: true
